### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by karl-police** [Tigernauts/Tigernauts.github.io#1]
How did you create this? https://github.com/Tigernauts/Tigernauts.github.io/blob/main/hex.js

Like from where did you know how to calculate it?

**Comment by Tygernaut** [comment]
for example there
https://en.wikipedia.org/wiki/Endianness
https://www.freecodecamp.org/news/what-is-endianness-big-endian-vs-little-endian/

**Comment by karl-police** [comment]
> for example there https://en.wikipedia.org/wiki/Endianness https://www.freecodecamp.org/news/what-is-endianness-big-endian-vs-little-endian/

so that's how you got formulas for easily calculating this?
